### ISSUE TITLE
Conform to TA3 engagement requirements

### ISSUE THREAD

**Issue by emaadmanzoor** [sbustreamspot/sbustreamspot-cdm#1]
**Meta:**
- Moved from a previous [issue](https://github.com/sbustreamspot/sbustreamspot-core/issues/31).
- Code moved from this [gist](https://gist.github.com/emaadmanzoor/b23d46c9d4d064746e1ef667cb8070bc)
- The previous issue contains graph visualisations and notes.
- Testing is done using `infoleaks_small_units.avro`. Larger Avro files are too difficult for my laptop.

**Tasks:**
- [x] Identify how edges construct graphs (we no longer have graph ID's)
- [x] sbustreamspot-cdm: combine CDM records into a StreamSpot edge.
- [x] sbustreamspot-cdm: visualise graphs.
- [x] sbustreamspot-cdm: assign graph IDs.
- [x] sbustreamspot-cdm: visualise graphs after assigning graph IDs.
- [x] sbustreamspot-cdm: Read CDM/Avro (currently reads CDM/JSON).
- [x] sbustreamspot-cdm: Read CDM/Avro from Kafka (currently reads a flat file).
- [x] sbustreamspot-train: Read training data in CDM/Avro, create shingle vectors (parameterised by C).
- [x] sbustreamspot-train: Cluster shingle vectors, determine k, output seed clustering.
- [x] sbustreamspot-core: Read seed clustering.
- [x] sbustreamspot-core: Do not assume a fixed total number of graphs.
- [x] sbustreamspot-core: Output anomaly score in the PAAS format on each edge.
- [x] Dockerize and document entire train/test process.

**Comment by emaadmanzoor** [comment]
Merging https://github.com/sbustreamspot/sbustreamspot-cdm/pull/2 adds CDM13 support for Avro/JSON-serialised files.

**Comment by emaadmanzoor** [comment]
Merging https://github.com/sbustreamspot/sbustreamspot-cdm/pull/3 adds CDM13 support for Avro-serialised data from Kafka.

**Comment by emaadmanzoor** [comment]
Complete.
